### ISSUE TITLE
US03 - Eu como usuário desejo navegar pelo feed de conteúdo para que consigar ver todos os post em um só lugar.

### ISSUE THREAD

**Issue by icarooliv** [Requisitos2017-2/Tumblr#1]
**US03** - Eu como usuário desejo navegar pelo feed de conteúdo para que consigar ver todos os post em um só lugar.

#### _**Tasks**_

- [ ] . Criar uma área para a navegação no feed de conteúdo.

- [ ] . Suporte para diferentes tipos de mídia.

- [ ] . Recuperar posts do banco de dados.

#### Critérios de Aceitação

- [ ] . O usuário deve ser capaz de visualizar e navegar o feed de conteúdo.

- [ ] . O código adicionado deve ser testado.

**Responsáveis:** Ícaro Oliveira e Fernando Aguilar
